List<String> tags = [
  "concert",
  "festival",
  "exposition",
  "théâtre",
  "cinéma",
  "conférence",
  "atelier",
  "séminaire",
  "webinaire",
  "cours de danse",
  "cours de cuisine",
  "tournoi sportif",
  "match de football",
  "match de basketball",
  "match de tennis",
  "marathon",
  "salon professionnel",
  "foire",
  "marché de Noël",
  "carnaval",
  "parade",
  "projection de film",
  "dégustation de vin",
  "soirée à thème",
  "bal",
  "rave",
  "festival de musique",
  "festival de cinéma",
  "festival de théâtre",
  "festival de danse",
  "festival de littérature",
  "rencontre littéraire",
  "bourse aux livres",
  "signature de livre",
  "rencontre d'auteur",
  "séance de dédicace",
  "projection de documentaire",
  "vernissage",
  "conférence de presse",
  "lancement de produit",
  "inauguration",
  "réception",
  "gala",
  "remise de prix",
  "foire d'art",
  "concert de musique classique",
  "concert de jazz",
  "concert de rock",
  "concert de pop",
  "concert de musique électronique",
  "concert de hip-hop",
  "spectacle de danse",
  "spectacle de magie",
  "spectacle de cirque",
  "comédie musicale",
  "pièce de théâtre",
  "one-man show",
  "stand-up",
  "atelier de peinture",
  "atelier de sculpture",
  "atelier de photographie",
  "atelier de dessin",
  "cours de yoga",
  "cours de méditation",
  "cours de fitness",
  "cours de pilates",
  "cours de natation",
  "cours de voile",
  "cours d'escalade",
  "randonnée",
  "trekking",
  "excursion",
  "sortie en bateau",
  "croisière",
  "camping",
  "pique-nique",
  "barbecue",
  "chasse au trésor",
  "escape game",
  "jeux de société",
  "tournoi de poker",
  "tournoi de jeux vidéo",
  "lan party",
  "conférence sur la technologie",
  "conférence sur la santé",
  "conférence sur l'environnement",
  "conférence sur l'économie",
  "conférence sur la politique",
  "conférence sur la science",
  "conférence sur l'histoire",
  "conférence sur la culture",
  "conférence sur les arts",
  "conférence sur le développement personnel",
  "séminaire de formation",
  "atelier d'écriture",
  "atelier de théâtre",
  "atelier de musique",
  "atelier de danse",
  "atelier de cuisine",
  "atelier de jardinage",
  "atelier de bricolage"
];

List<String> userTags = [];
